language: python
sudo: false
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
install: pip install -r examples/python/requirements.txt
script: python examples/python/diagnostic_tools.py --config_file .edgerc --verbose
before_install:
- openssl aes-256-cbc -K $encrypted_d93385c721d4_key -iv $encrypted_d93385c721d4_iv
  -in .edgerc.enc -out .edgerc -d
