language: python
sudo: false
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
install: 
- pip install --upgrade pip
- pip install -r examples/python/requirements.txt
script: 
- python examples/python/diagnostic_tools.py --verbose
- examples/php/diagnostic_tools.php
- exmaplels/ruby/diagnostic_tools.rb
before_install:
- openssl aes-256-cbc -K $encrypted_d93385c721d4_key -iv $encrypted_d93385c721d4_iv
  -in .edgerc.enc -out .edgerc -d
- mv .edgerc /home/travis

