language: python
sudo: required
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
install: 
- pip install --upgrade pip
- pip install -r examples/python/requirements.txt
- sudo apt-get -y update
- sudo apt-get -7 -y install php5 php5-mhash php5-mcrypt php5-curl php5-cli php5-mysql php5-gd php5-intl php5-xsl perl ruby1.9.3
script: 
- python examples/python/diagnostic_tools.py --verbose
- php -version
- php5 examples/php/diagnostic_tools.php
- ruby examples/ruby/diagnostic_tools.rb
before_install:
- openssl aes-256-cbc -K $encrypted_d93385c721d4_key -iv $encrypted_d93385c721d4_iv
  -in .edgerc.enc -out .edgerc -d
- mv .edgerc /home/travis

