language: python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
install: 
- pip install --upgrade pip
- pip install -r examples/python/requirements.txt
script: 
- cat /home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/akamai/edgegrid/edgegrid.py
- python examples/python/diagnostic_tools.py --verbose
before_install:
- openssl aes-256-cbc -K $encrypted_d93385c721d4_key -iv $encrypted_d93385c721d4_iv
  -in .edgerc.enc -out .edgerc -d
- mv .edgerc /home/travis

